---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_php"
      tags:
        - "labocbz.install_php"
      vars:
        install_php_version: "{{ inv_install_php_version }}"
        install_php_version_is_default: "{{ inv_install_php_version_is_default }}"
        install_php_extensions: "{{ inv_install_php_extensions }}"
        install_php_install_fpm: "{{ inv_install_php_install_fpm }}"
        install_php_import_cli_conf: "{{ inv_install_php_import_cli_conf }}"
        install_php_import_apache_conf: "{{ inv_install_php_import_apache_conf }}"
        install_php_import_cgi_conf: "{{ inv_install_php_import_cgi_conf }}"
        install_php_import_fpm_conf: "{{ inv_install_php_import_fpm_conf }}"
        install_php_max_input_time: "{{ inv_install_php_max_input_time }}"
        install_php_output_buffering: "{{ inv_install_php_output_buffering }}"
        install_php_cgi_fix_pathinfo: "{{ inv_install_php_cgi_fix_pathinfo }}"
        install_php_expose_php: "{{ inv_install_php_expose_php }}"
        install_php_max_execution_time: "{{ inv_install_php_max_execution_time }}"
        install_php_memory_limit: "{{ inv_install_php_memory_limit }}"
        install_php_post_max_size: "{{ inv_install_php_post_max_size }}"
        install_php_file_uploads: "{{ inv_install_php_file_uploads }}"
        install_php_upload_max_filesize: "{{ inv_install_php_upload_max_filesize }}"
        install_php_max_file_uploads: "{{ inv_install_php_max_file_uploads }}"
        install_php_allow_url_fopen: "{{ inv_install_php_allow_url_fopen }}"
        install_php_allow_url_include: "{{ inv_install_php_allow_url_include }}"
        install_php_session_save_handler: "{{ inv_install_php_session_save_handler }}"
        install_php_session_save_path: "{{ inv_install_php_session_save_path }}"
        install_php_session_auto_start: "{{ inv_install_php_session_auto_start }}"
        install_php_session_use_strict_mode: "{{ inv_install_php_session_use_strict_mode }}"
        install_php_disable_functions: "{{ inv_install_php_disable_functions }}"
        install_php_remove_all_fpm_pools: "{{ inv_install_php_remove_all_fpm_pools }}"
        install_php_fpm_pools_path: "{{ inv_install_php_fpm_pools_path }}"
      ansible.builtin.include_role:
        name: "labocbz.install_php"
