---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_php"
      tags:
        - "labocbz.install_php"
      vars:
        install_php_version: "{{ inv_install_php_version }}"
        install_php_version_is_default: "{{ inv_install_php_version_is_default }}"
        install_php_extensions: "{{ inv_install_php_extensions }}"
      ansible.builtin.include_role:
        name: "labocbz.install_php"
